-- 1. Create Roles and Setup Auth Extension
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('admin', 'staff');
  END IF;
END $$;

-- 2. Profiles table (linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role user_role DEFAULT 'staff',
  full_name TEXT,
  avatar_url TEXT DEFAULT 'https://i.pravatar.cc/150',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tours table
CREATE TABLE IF NOT EXISTS public.tours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  departure_date TIMESTAMPTZ,
  status TEXT CHECK (status IN ('pending', 'upcoming', 'completed')) DEFAULT 'pending',
  assigned_to UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Availability table
CREATE TABLE IF NOT EXISTS public.availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Messages table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.profiles(id),
  channel_name TEXT DEFAULT 'general',
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 7. Policies (Use DO blocks or DROP if exists to avoid "already exists" errors)
DO $$ 
BEGIN
  -- Profiles
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public profiles are viewable by everyone.') THEN
    CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (TRUE);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can update profiles.') THEN
    CREATE POLICY "Admins can update profiles." ON public.profiles 
    FOR UPDATE USING (auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));
  END IF;

  -- Tours
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Staff view their tours') THEN
    CREATE POLICY "Staff view their tours" ON public.tours 
    FOR SELECT USING (assigned_to = auth.uid() OR auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));
  END IF;

  -- Availability
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Staff manage their availability') THEN
    CREATE POLICY "Staff manage their availability" ON public.availability 
    FOR ALL USING (staff_id = auth.uid() OR auth.uid() IN (SELECT id FROM public.profiles WHERE role = 'admin'));
  END IF;

  -- Messages
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth users can read messages') THEN
    CREATE POLICY "Auth users can read messages" ON public.messages FOR SELECT TO authenticated USING (TRUE);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth users can insert messages') THEN
    CREATE POLICY "Auth users can insert messages" ON public.messages FOR INSERT TO authenticated WITH CHECK (sender_id = auth.uid());
  END IF;
END $$;

-- 8. Trigger to auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', 'staff');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop and recreate the trigger to avoid errors
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9. SEED DATA (Only if table is empty)
INSERT INTO public.tours (title, departure_date, status)
SELECT t.title, t.dep, t.stat
FROM (VALUES 
  ('Grand Canyon 3-Day', now() + interval '1 day', 'pending'),
  ('Yosemite Trek', now() + interval '10 days', 'upcoming'),
  ('Zion Day Trip', now() - interval '2 days', 'completed')
) AS t(title, dep, stat)
WHERE NOT EXISTS (SELECT 1 FROM public.tours);
